encode:
  code:
    string: ~

parse:
  type: csv
  unflatten:
    separator: '-'
  nullify: ~
  reference: code
  format:
    delimiter: ';'
    enclosure: '"'

validations:
  include: 'validation/association_type.yaml'