FROM docker.io/library/debian:bullseye-slim

ENV DEBIAN_FRONTEND="noninteractive" \
    OS_ARCH="amd64" \
    OS_FLAVOUR="debian-11" \
    OS_NAME="linux" \
    HOME="/build" \
    LANGUAGE="en_US.UTF-8" \
    LC_ALL="C.UTF-8" \
    LANG="en_US.UTF-8" \
    TERM="xterm"

RUN apt-get update && \
    echo "**** install useful distro packages ****" && \
    apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
        apt-transport-https \
        lsb-release \
        ca-certificates \
        bash-completion \
        gnupg \
        procps \
        wget \
        curl \
        less \
        make \
        htop \
        ssh-client \
        openssh-client \
        vim \
        nano \
        unzip \
        cron \
        systemd-sysv \
        perceptualdiff && \
    apt-get clean && apt-get --yes --quiet autoremove --purge && \
    rm -rf  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            /usr/share/doc/* /usr/share/groff/* /usr/share/info/* /usr/share/linda/* \
            /usr/share/lintian/* /usr/share/locale/* /usr/share/man/*

# Add Sury PHP repository
RUN wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
COPY files/sury.list /etc/apt/sources.list.d/sury.list

# install app oriented dependencies with extensions
RUN apt-get update && \
    apt-get --no-install-recommends --no-install-suggests --yes --quiet install \
        imagemagick \
        default-mysql-client \
        php8.1-fpm \
        php8.1-cli \
        php8.1-intl \
        php8.1-opcache \
        php8.1-mysql \
        php8.1-zip \
        php8.1-xml \
        php8.1-gd \
        php8.1-curl \
        php8.1-redis \
        php8.1-mbstring \
        php8.1-bcmath \
        php8.1-imagick \
        php8.1-apcu \
        php8.1-exif && \
    apt-get clean && apt-get --yes --quiet autoremove --purge && \
    rm -rf  /var/lib/apt/lists/* /tmp/* /var/tmp/* \
            /usr/share/doc/* /usr/share/groff/* /usr/share/info/* /usr/share/linda/* \
            /usr/share/lintian/* /usr/share/locale/* /usr/share/man/*

# create a build user and home-directory, setup a app directory
RUN useradd -u 911 -U -d /build -s /bin/bash build && \
    usermod -G users build && \
    mkdir -p \
	/build/app && \
    chown build:www-data /build -R

COPY files/php/app.conf /etc/php/8.1/fpm/pool.d/
COPY files/php/app.ini /etc/php/8.1/mods-available/app.ini
COPY files/php/cli-conf.ini /etc/php/8.1/cli/conf.d/99-pim.ini
COPY files/php/fpm-conf.ini /etc/php/8.1/fpm/conf.d/99-pim.ini
RUN rm /etc/php/8.1/fpm/pool.d/www.conf && phpenmod app

#RUN phpenmod app
#COPY files/nginx /etc/nginx/sites-available/
#RUN rm /etc/nginx/sites-enabled/default; ln -s /etc/nginx/sites-available/prod.conf /etc/nginx/sites-enabled/prod.conf

# cron & cron wrapper
#USER build
#COPY files/app.crons /build/scripts/cronfile
#RUN crontab /build/scripts/cronfile
#
#USER root

#EXPOSE 80

RUN systemctl enable php8.1-fpm
#; systemctl enable nginx

CMD [ "/sbin/init" ]

COPY --chown=build:www-data project /build/app
